library/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('',include('mainApp.urls')),
]

mainApp/urls.py
from django.urls import path,include
from . import views
app_name = 'mainApp'
urlpatterns = [
    path('', views.home, name="Главная страница"),
    path('about/', views.about, name="О нас"),
    path('genres/', views.genre, name="Жанры"),
    path('genres/<str:name_genre>_<int:genre_id>/', views.genre_detail, name="genre_detail"),
    path('<str:name_book>_<int:book_id>/', views.book_detail, name="book_detail"),
    path('<str:name_book>_<int:book_id>/leave_comment', views.leave_comment, name="leave_comment"),
    path('search/', views.search_books, name="search_books")
]

catalog/models.py
from django.db import models

# Create your models here.

mainApp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Book_series(models.Model):
   name_series = models.CharField('Название серии', max_length = 50)
   image_series = models.ImageField(upload_to = 'static', blank=True)
   def __str__(self):
       return self.name_series

class Genre(models.Model):
    name_genre = models.CharField('Жанр', max_length = 50)
    def __str__(self):
        return self.name_genre

class Author(models.Model):
    name_author = models.CharField('Имя автора', max_length = 50)
    biographi = models.CharField('Биография', max_length = 500)
    def __str__(self):
        return self.name_author

class Book(models.Model):
    """docstring for Book."""

    series = models.ForeignKey(Book_series, on_delete = models.CASCADE, null=True)
    name_book = models.CharField('Название книги', max_length = 50)
    annotation = models.CharField('Аннотация к книге', max_length = 300, blank=True)
    publication_date = models.DateTimeField('Дата публицации')
    genres_book = models.ManyToManyField(Genre, verbose_name="Жанры книги")
    authors = models.ManyToManyField(Author, verbose_name="Авторы")
    image_book = models.ImageField(upload_to = 'static', blank=True)
    def __str__(self):
        return self.name_book


class Comment(models.Model):
    """docstring for comment."""
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    author_name = models.CharField('Псевдоним', max_length = 20)
    comment_text = models.CharField('Текст комментария', max_length = 300)

    def __str__(self):
        return self.author_name

class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    name_chapter = models.CharField('Название главы', max_length = 30)
    chapter_text = models.TextField('Содержание главы')

    def __str__(self):
        d = Book.objects.get(name_book = self.book)
        return   d.name_book+' '+self.name_chapter

class Image_chapter(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete = models.CASCADE)
    Image_chapter = models.ImageField(upload_to = 'static')
    def __str__(self):
        return self.image_chapter_directory

class Book_raiting(models.Model):
    book = models.ForeignKey(Book, on_delete = models.CASCADE)

catalog/views.py
from django.shortcuts import render

# Create your views here.

mainApp/views.py
from django.shortcuts import render
from .models import Book,Chapter,Book_series,Genre
from  django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q

# Create your views here.
import parser
def home (request):
    book = Book.objects.order_by('-publication_date')
    return render(request, 'mainApp/homePage.html',{'book': book})

def about(request):
    return render(request, 'mainApp/about.html')

def book_detail(request, name_book , book_id ):
    try:
        b = Book.objects.get(id = book_id)
    except:
        raise Http404("Книга не найдена!")
    if (name_book != b.name_book):
        raise Http404("Книга не найдена!")
    chapters = Chapter.objects.filter(book = b.id)
    chapters = chapters.order_by("name_chapter")
    another_book = Book.objects.filter(series = b.series)
    another_book = another_book.exclude(id = b.id)
    series = Book_series.objects.get(name_series = b.series)
    comment = b.comment_set.order_by('-id')[:10]
    return render(request, 'mainApp/book.html', {'book':b, 'chapter':chapters, 'another_book_in_series':another_book, 'series':series , 'comment':comment})

def genre(request):
    genres = Genre.objects.all()
    return render(request, 'mainApp/genres.html', {'genres': genres})

def genre_detail(request, name_genre, genre_id):
    try:
        g = Genre.objects.get(id = genre_id)
    except:
        raise Http404("Жанр не найден!")
    if (name_genre != g.name_genre):
        raise Http404("Жанр не найден!")
    book = Book.objects.filter(genres_book__id = genre_id )
    return render(request, 'mainApp/homePage.html', {'book':book})

def leave_comment(request, name_book, book_id):
    try:
        b = Book.objects.get(id = book_id)
    except:
        raise Http404("Книга не найдена!")
    b.comment_set.create(author_name = request.POST.get('name', False), comment_text = request.POST.get('text', False))
    return HttpResponseRedirect(reverse('mainApp:book_detail',args = (b.name_book, b.id,)))

def search_books(request):
    try:
        b = Book.objects.filter(Q(name_book__icontains = request.POST.get('search',False)) | Q(authors__name_author__icontains = request.POST.get('search',False)))
    except:
        raise Http404("Книг не найдено!")
    return render(request, 'mainApp/homePage.html', {'book':b})

mainApp/templates/mainApp/about.html
{% extends "mainApp/wrapper.html"%}

{% block content %}
<div class="jumotron container">

  <div style="background-color:#00ccff">
    <h1>О нас</h1>
    <p>Данный сайт разработан студентом 3 курса факультета Компьютерных технологий и Прикладной математики Кубанского годударственного университета</p>
    <p>Данный сайт является курсовой работой Старостенко Эльдара Владимировича</p>
  </div>
</div>
{% endblock %}

mainApp/templates/mainApp/book.html
{% extends "mainApp/wrapper.html"%}
{% block content %}
<div class="container-fluid  oflow" >
  <div class="row">
<div >
  <h1></h1>
</div>
<div  style="background-color:#cccccc">
<div class="col-xs-12 col-sm-12 col-md-12 " >

    <a href="{% url 'mainApp:book_detail' book.name_book book.id %}" style = "color:#000000"><h2>

      {{book.name_book}}
      </h2>
    </a>

</div>
<div class="col-xs-12 col-sm-6 col-md-3" >
  {% if book.image_book %}
    <img src="../{{book.image_book.url}}" class="img-fluid" width="240" height="343" align="left">
{% else %}
  <img src="/static/book-question-mark-computer-icons-clip-art-earth-globe.jpg" class="img-fluid" width="240" height="343" align="left">
{% endif %}

 </div>
 <div class="col-xs-12 col-sm-8 col-md-12 " >
 <p>{{book.annotation}}</p>
 <h5>Авторы:</h5>
 {% for auth in book.authors.all %}
 <p>{{auth.name_author}}</p>
 {% endfor %}

 <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Главы
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for chp in chapter %}
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#a{{chp.id}}">
  {{chp.name_chapter}}
    </button>
    {% endfor %}
  </div>
</div>

<h5>Другие книги из серии: {{series.name_series}}</h5>

<p>
{% for another in another_book_in_series %}
<div class="container-fluid  oflow">
  <a href="{% url 'mainApp:book_detail' another.name_book another.id %}" style = "color:#000000">{{another.name_book}}</a>
  </div>
{% endfor %}

 </div>
 </div>
 <h3>Комментарии:</h3>
 {% for com in comment %}
 <div class="container-fluid  oflow">

     <div class="media">
     <div class="media-body">
       <h5 class="mt-0">{{com.author_name}}:</h5>
         <p>{{com.comment_text}}</p>
     </div>
   </div>
   </div>
 {% endfor %}
 <hr>
 <h1></h1>
 <form action="{% url 'mainApp:leave_comment' book.name_book book.id %}" method="POST" >
   {% csrf_token %}

   <div class="form-group">
       <label for="exampleFormControlInput1">Ник</label>
       <input type="text" class="form-control" id="exampleFormControlInput1" placeholder = "Ваше имя" name="name">
     </div>

     <div class="form-group">
         <label for="exampleFormControlTextarea1">Текст комментария</label>
         <textarea  class="form-control" name="text" required placeholder = "Текст комментария" id="exampleFormControlTextarea1" rows="3"></textarea>
       </div>
       <button type="submit" class="btn btn-outline-primary">Отправить</button>

 </form>
 {% for chp in chapter %}
 <div class="modal fade" id="a{{chp.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
<div class="modal-dialog modal-lg " role="document">
 <div class="modal-content">
   <div class="modal-header">
     <h5 class="modal-title" id="{{chp.id}}">{{chp.name_chapter}}</h5>
     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
   <div class="modal-body">
     <p>{{chp.chapter_text}}</p>

   </div>
   <div class="modal-footer">
     <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
   </div>
 </div>
</div>
</div>
{% endfor %}
{% endblock %}

mainApp/templates/mainApp/genres.html
{% extends "mainApp/wrapper.html"%}
{% block content %}

  {% for genr in genres %}
    <a href="{% url 'mainApp:genre_detail' genr.name_genre genr.id %}" style = "color:#000000">
      <h2>
        {{genr.name_genre}}
      </h2>
    </a>
  {% endfor %}

{% endblock %}

mainApp/templates/mainApp/homePage.html
{% extends "mainApp/wrapper.html"%}
{% block content %}
<div class="container-fluid  oflow" >
  <div class="row">


{% if not book %}
<h2>Книги по запросу не найдены</h2>
{% endif%}
{% for val in book %}
<div >
  <h1></h1>
</div>
<div  style="background-color:#cccccc">


<div class="col-xs-12 col-sm-12 col-md-12 " >

    <a href="{% url 'mainApp:book_detail' val.name_book val.id %}" style = "color:#000000"><h2>

      {{val.name_book}}
      </h2>
    </a>

</div>
<div class="col-xs-12 col-sm-6 col-md-3" >
  {% if val.image_book %}
    <img src="../../{{val.image_book.url}}" class="img-fluid" width="240" height="343" align="left">
{% else %}
  <img src="/static/book-question-mark-computer-icons-clip-art-earth-globe.jpg" class="img-fluid" width="240" height="343" align="left">
{% endif %}
 </div>
 <div class="col-xs-12 col-sm-8 col-md-12 " >
 <p>{{val.annotation}}</p>
 <h5>Авторы:</h5>
 {% for auth in val.authors.all %}
 <p>{{auth.name_author}}</p>
 {% endfor %}
 <h5>Жанры:</h5>
 <p>
 {% for gen in val.genres_book.all %}
 {{gen.name_genre}},
 {% endfor %}
 </p>
 </div>
 </div>
{% endfor %}
{% endblock %}

mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<style>
  .oflow {
  word-wrap: break-word;
}

</style>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Читалка</title>
    <link rel="shortcut icon" href="/static/logo.svg" type="image/x-icon">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body >


    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
          <a href="/" class = "navbar-brand">
             <img src="/static/logo.svg" width="30" height="30" alt="">
            Читалка
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02" >
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item "> <a class= "nav-link" href="/">Главная</a> </li>
                <li class="nav-item"> <a class= "nav-link" href="/genres">Жанры</a> </li>
                <li class="nav-item"> <a class= "nav-link" href="/about">О нас</a> </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'mainApp:search_books'  %}" method="POST">
            {% csrf_token %}
             <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Search" name = "search">
             <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
           </form>
        </div>
    </nav>
    <div class="row">
      <div class="col-xs-0 col-sm-1 col-md-2 col-lg-2"></div>
        <div class="col-xs-12 col-sm-10 col-md-6 col-lg-6">
    {% block content %}
    {% endblock %}
      </div>
      <div class="col-xs-0 col-sm-1 col-md-4 col-lg-4"><p></p></div>
      </div>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>